### ISSUE TITLE
增加对Android版本的支持

### ISSUE THREAD

**Issue by amokiel** [asadahimeka/pixiv-viewer#1]
总体体验很不错，应用网站推荐都很实用，谢谢推荐。不过移动端用浏览器阅览总感觉不太习惯。希望您可以考虑出个Android版本，这样在移动端体验会更好一些。多谢，辛苦啦！

**Comment by asadahimeka** [comment]
网站支持 PWA 的，可以使用支持 PWA 的浏览器直接安装到桌面，比如 Chrome、Edge或者小米自带的浏览器；
Android 版本的话就是套个 webview，体验上跟 PWA 差不太多，[原版](https://github.com/journey-ad/pixiv-viewer) 是有 apk 安装包的，我有空再看看

**Comment by asadahimeka** [comment]
Android 开发不在本人能力范围之内 <img src="https://user-images.githubusercontent.com/31837214/214237746-f3a5420f-9f2e-4eff-b5a4-ce2cb483a6c2.png" width=24>，想要 Android 版的话可以使用 [PixEz](https://github.com/Notsfsssf/pixez-flutter) 哈，我平常都在用这个的
