### ISSUE TITLE
artworks页面推荐条目数量远少于pixiv主站

### ISSUE THREAD

**Issue by continue-revolution** [asadahimeka/pixiv-viewer#17]
首先很感谢开发并维护此项目和yandere masonry，对我帮助很大。

我观察到此项目和upstream的artwork页面的相关作品要远少于pixiv主站的推荐条目，如[此页面](https://www.pixiv.net/artworks/112473280)在pixiv下的推荐多达150张左右，然而[您的项目](https://www.pixiv.pics/artworks/112473280)相关推荐仅有30多张。唯pixiv主站的预览图全都被切割过，实在难以使用。

不知是否有办法能让您的项目的相关推荐可以和主站一样多，且预览图没有被裁切过。

**Comment by asadahimeka** [comment]
看了一下这个问题应该是 HibiAPI 获取相关作品的实现有些问题，我改了下，网页版 v1.18.2 已发布。
因为只修改了我自己的 API 的实例，所有如果没有使用 OAuth/RefreshToken 登录或者设置的 API 实例不是默认的话，获取相关作品的行为还是不正常的。

![www pixiv pics_artworks_112473280](https://github.com/user-attachments/assets/3f8f6715-ab46-42ef-916c-3af97578dd10)
