### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by yingyue064** [asadahimeka/pixiv-viewer#4]
您好，我在按照指示获取session ID后保存，提示请求出错

**Comment by asadahimeka** [comment]
SessionID 登录使用的是 Ajax API，可能会有些问题；目前建议使用 RefreshToken 登录调用 App API

**Comment by yingyue064** [comment]
感谢您的回答，不过我在Pixiv-Viewer-1.9.0-win并未发现RefreshToken 登录，静待您的更新
